## Install

In [1]:
!pip install ydata-profiling setuptools pandas google-cloud-bigquery google-auth pyarrow

Defaulting to user installation because normal site-packages is not writeable
Collecting ydata-profiling
  Downloading ydata_profiling-4.17.0-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Requirement already satisfied: pandas in /home/dongtd6/.local/lib/python3.10/site-packages (2.3.2)
Collecting google-cloud-bigquery
  Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: google-auth in /home/dongtd6/.local/lib/python3.10/site-packages (2.40.3)
Requirement already satisfied: pyarrow in /home/dongtd6/.local/lib/python3.10/site-packages (20.0.0)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from ydata-profiling) (1.15.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pydantic>=2 (from ydata-profiling)
  Downloading pydantic-2.12.3-py3-none-any.whl.metadata (87 kB)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2.2,>=1.16.0 (from ydata-profiling)
  Downloading numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.5-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from ydata-profiling) (2.32.5)
Collecting tqdm<5,>=4.48.2 (from ydata-profiling)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting seaborn<0.14,>=0.10.1 (from ydata-profiling)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=3 (from ydata-profiling)
  Downloading typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.3 (from ydata-profiling)
  Downloading wordcloud-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<=0.61,>=0.56.0 (from ydata-profiling)
  Downloading numba-0.61.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from imagehash==4.3.1->ydata-profiling) (9.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/dongtd6/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/dongtd6/.local/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/dongtd6/.local/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.4.7)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba<=0.61,>=0.56.0->ydata-profiling)
  Downloading llvmlite-0.44.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: joblib>=0.14.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/dongtd6/.local/lib/python3.10/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2020.6.20)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from typeguard<5,>=3->ydata-profiling) (4.14.0)
Requirement already satisfied: attrs>=19.3.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /home/dongtd6/.local/lib/python3.10/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Collecting google-api-core<3.0.0,>=2.11.1 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading google_api_core-2.28.1-py3-none-any.whl.metadata (3.3 kB)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery)
  Downloading google_cloud_core-2.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery)
  Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-auth) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-auth) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-auth) (4.9.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.59.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (5.29.5)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /home/dongtd6/.local/lib/python3.10/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.73.1)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
Collecting google-crc32c<2.0dev,>=1.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery)
  Downloading google_crc32c-1.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.71.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.70.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.69.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.68.1-py3-none-any.whl.metadata (1.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading grpcio_status-1.68.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.67.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.67.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.66.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.66.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.66.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.65.5-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.65.4-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.65.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.65.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.64.3-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.64.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.64.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.63.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.63.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.62.3-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/dongtd6/.local/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth) (0.6.1)
Collecting annotated-types>=0.6.0 (from pydantic>=2->ydata-profiling)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.4 (from pydantic>=2->ydata-profiling)
  Downloading pydantic_core-2.41.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing_extensions>=4.14.0 (from typeguard<5,>=3->ydata-profiling)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic>=2->ydata-profiling)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Downloading ydata_profiling-4.17.0-py2.py3-none-any.whl (399 kB)
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Downloading matplotlib-3.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 2.4 MB/s  0:00:03 eta 0:00:01
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.61.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 2.6 MB/s  0:00:01 eta 0:00:01
Downloading llvmlite-0.44.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 2.8 MB/s  0:00:14m0:00:0100:01
Downloading numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 4.8 MB/s  0:00:03 eta 0:00:01
Downloading phik-0.12.5-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (677 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 677.6/677.6 kB 3.3 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading statsmodels-0.14.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 4.9 MB/s  0:00:02 eta 0:00:01
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading typeguard-4.4.4-py3-none-any.whl (34 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl (259 kB)
Downloading google_api_core-2.28.1-py3-none-any.whl (173 kB)
Downloading google_cloud_core-2.5.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl (81 kB)
Downloading google_crc32c-1.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38 kB)
Downloading grpcio_status-1.62.3-py3-none-any.whl (14 kB)
Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 4.6 MB/s  0:00:00 eta 0:00:01
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading pydantic-2.12.3-py3-none-any.whl (462 kB)
Downloading pydantic_core-2.41.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.0 MB/s  0:00:00 eta 0:00:01
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading wordcloud-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511 kB)
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
Downloading pywavelets-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 4.7 MB/s  0:00:00 eta 0:00:01
Installing collected packages: puremagic, minify-html, filetype, typing_extensions, tqdm, protobuf, numpy, multimethod, llvmlite, google-crc32c, dacite, annotated-types, typing-inspection, typeguard, PyWavelets, pydantic-core, proto-plus, patsy, numba, google-resumable-media, visions, statsmodels, pydantic, matplotlib, imagehash, grpcio-status, google-api-core, wordcloud, seaborn, phik, google-cloud-core, ydata-profiling, google-cloud-bigquery
  Attempting uninstall: typing_extensions━━━━━━━━━━━━━━━━━━━━━━━━━  1/33 [minify-html]
    Found existing installation: typing_extensions 4.14.0━━━━━  1/33 [minify-html]
    Uninstalling typing_extensions-4.14.0:━━━━━━━━━━━━━━━━━━━━  1/33 [minify-html]
      Successfully uninstalled typing_extensions-4.14.0━━━━━━━━━━━  3/33 [typing_extensions]
  Attempting uninstall: protobuf━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/33 [typing_extensions]
    Found existing installation: protobuf 5.29.5━━━━━━━━━━━━━━  3/33 [typing_extensions]
    Uninstalling protobuf-5.29.5:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/33 [typing_extensions]
      Successfully uninstalled protobuf-5.29.5━━━━━━━━━━━━━━━━  3/33 [typing_extensions]
  Attempting uninstall: numpy[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/33 [protobuf]ions]
    Found existing installation: numpy 2.2.6━━━━━━━━━━━━━━━━━━  5/33 [protobuf]
    Uninstalling numpy-2.2.6:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/33 [numpy]
      Successfully uninstalled numpy-2.2.6━━━━━━━━━━━━━━━━━━━━  6/33 [numpy]
  Attempting uninstall: pydantic━╺━━━━━━━━━━━━━━ 21/33 [statsmodels]
    Found existing installation: pydantic 1.10.22━━━━━━━━━━━━━ 21/33 [statsmodels]
    Uninstalling pydantic-1.10.22:[90m╺━━━━━━━━━━━━━━ 21/33 [statsmodels]
      Successfully uninstalled pydantic-1.10.22m━━━━━━━━━━━━━━ 21/33 [statsmodels]
  Attempting uninstall: matplotlib╸━━━━━━━━━━━━━ 22/33 [pydantic]
    Found existing installation: matplotlib 3.10.3━━━━━━━━━━━━ 22/33 [pydantic]
    Uninstalling matplotlib-3.10.3:[91m╸━━━━━━━━━━━━━ 22/33 [pydantic]
      Successfully uninstalled matplotlib-3.10.3m━━━━━━━━━━━━ 23/33 [matplotlib]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33/33 [google-cloud-bigquery]le-cloud-bigquery]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dbt-adapters 1.13.2 requires protobuf<6.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
dbt-common 1.27.1 requires protobuf<6.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
dbt-core 1.9.1 requires protobuf<6.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
fastapi 0.96.0 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 2.12.3 which is incompatible.
Successfully installed PyWavelets-1.8.0 annotated-types-0.7.0 dacite-1.9.2 filetype-1.2.0 google-api-core-2.28.1 google-cloud-bigquery-3.38.0 google-cloud-core-2.5.0 google-crc32c-1.7.1 google-resumable-media-2.7.2 grpcio-status-1.62.3 imagehash-4.3.1 llvmlite-0.44.0 matplotlib-3.10.0 minify-html-0.18.1 multimethod-1.12 numba-0.61.0 numpy-2.1.3 patsy-1.0.2 phik-0.12.5 proto-plus-1.26.1 protobuf-4.25.8 puremagic-1.30 pydantic-2.12.3 pydantic-core-2.41.4 seaborn-0.13.2 statsmodels-0.14.5 tqdm-4.67.1 typeguard-4.4.4 typing-inspection-0.4.2 typing_extensions-4.15.0 visions-0.8.1 wordcloud-1.9.4 ydata-profiling-4.17.0

In [ ]:
import pandas as pd
import os
from ydata_profiling import ProfileReport
from google.cloud import bigquery
from google.oauth2 import service_account

## 0. Load Data

In [4]:
# Tạo DataFrame từ các file CSV
olist_orders_dataset = pd.read_csv('csv/olist_orders_dataset.csv')    
olist_customers_dataset = pd.read_csv('csv/olist_customers_dataset.csv')
olist_geolocation_dataset = pd.read_csv('csv/olist_geolocation_dataset.csv')
olist_order_payments_dataset = pd.read_csv('csv/olist_order_payments_dataset.csv')
product_category_name_translation = pd.read_csv('csv/product_category_name_translation.csv')
olist_order_items_dataset = pd.read_csv('csv/olist_order_items_dataset.csv')
olist_order_reviews_dataset = pd.read_csv('csv/olist_order_reviews_dataset.csv')
olist_products_dataset = pd.read_csv('csv/olist_products_dataset.csv')
olist_sellers_dataset = pd.read_csv('csv/olist_sellers_dataset.csv')

dfs = {
    "olist_orders_dataset": olist_orders_dataset,
    "olist_customers_dataset": olist_customers_dataset,
    "olist_geolocation_dataset": olist_geolocation_dataset,
    "olist_order_payments_dataset": olist_order_payments_dataset,
    "product_category_name_translation": product_category_name_translation,
    "olist_order_items_dataset": olist_order_items_dataset,
    "olist_order_reviews_dataset": olist_order_reviews_dataset,
    "olist_products_dataset": olist_products_dataset,
    "olist_sellers_dataset": olist_sellers_dataset
}

summary = pd.DataFrame([
    {"Tên DataFrame": name, "Số dòng": df.shape[0], "Số cột": df.shape[1]}
    for name, df in dfs.items()
])

#summary.sort_values(by="Tên DataFrame", inplace=True)
display(summary)

                       Tên DataFrame  Số dòng  Số cột
0               olist_orders_dataset    99441       8
1            olist_customers_dataset    99441       5
2          olist_geolocation_dataset  1000163       5
3       olist_order_payments_dataset   103886       5
4  product_category_name_translation       71       2
5          olist_order_items_dataset   112650       7
6        olist_order_reviews_dataset    99224       7
7             olist_products_dataset    32951       9
8              olist_sellers_dataset     3095       4

In [5]:
# Thông tin kết nối BigQuery
project_id = "fsds-469803"
dataset_id = "dwh_olist"
key_path = os.path.expanduser('~/BusinessIntelligence/fsds-469803-50393ed26312.json')

# Tạo client BigQuery
credentials = service_account.Credentials.from_service_account_file(key_path)
client = bigquery.Client(credentials=credentials, project=project_id)

# Cấu hình ghi đè bảng nếu đã tồn tại
job_config = bigquery.LoadJobConfig(
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,  #WRITE_APPEND,
    autodetect=True,  
)

# Load DataFrame vào BigQuery
table_id = "olist_orders_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_orders_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_customers_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_customers_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_geolocation_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_geolocation_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_order_payments_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_order_payments_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "product_category_name_translation"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(product_category_name_translation, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_order_items_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_order_items_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_order_reviews_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_order_reviews_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_products_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_products_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

table_id = "olist_sellers_dataset"
table_ref = f"{project_id}.{dataset_id}.{table_id}"
job = client.load_table_from_dataframe(olist_sellers_dataset, table_ref, job_config=job_config)
job.result()  
print(f"✅ Đã tải {job.output_rows} dòng vào bảng {table_ref}")

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 99441 dòng vào bảng fsds-469803.dwh_olist.olist_orders_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 99441 dòng vào bảng fsds-469803.dwh_olist.olist_customers_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 1000163 dòng vào bảng fsds-469803.dwh_olist.olist_geolocation_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 103886 dòng vào bảng fsds-469803.dwh_olist.olist_order_payments_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 71 dòng vào bảng fsds-469803.dwh_olist.product_category_name_translation

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 112650 dòng vào bảng fsds-469803.dwh_olist.olist_order_items_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 99224 dòng vào bảng fsds-469803.dwh_olist.olist_order_reviews_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 32951 dòng vào bảng fsds-469803.dwh_olist.olist_products_dataset

/home/dongtd6/BusinessIntelligence/ProjectFinal/BIFinalProject/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Đã tải 3095 dòng vào bảng fsds-469803.dwh_olist.olist_sellers_dataset

## 1. Check Data

In [6]:
olist_order_items_dataset.isna().all(axis=1).sum()
olist_order_items_dataset.duplicated().sum()

np.int64(0)

In [ ]:
# Kiểm tra giá trị null trong các DataFrame
null_summary = pd.DataFrame(columns=["Table", "Column", "Missing_Count", "Missing_%"])

for name, df in dfs.items():
    nulls = df.isnull().sum()
    total = len(df)
    percent = (nulls / total * 100).round(2)
    
    temp = pd.DataFrame({
        "Table": name,
        "Column": nulls.index,
        "Missing_Count": nulls.values,
        "Missing_%": percent.values
    })
    
    null_summary = pd.concat([null_summary, temp], ignore_index=True)

# Lọc chỉ những cột có giá trị null
null_summary = null_summary[null_summary["Missing_Count"] > 0]    

# Sắp xếp cho dễ đọc
null_summary = null_summary.sort_values(by=["Missing_%", "Table"], ascending=[False, True])

# Hiển thị bảng tóm tắt
display(null_summary)

/tmp/ipykernel_595240/634157809.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  null_summary = pd.concat([null_summary, temp], ignore_index=True)

,Table,Column,Missing_Count,Missing_%
35,olist_order_reviews_dataset,review_comment_title,87656,88.34
36,olist_order_reviews_dataset,review_comment_message,58247,58.70
6,olist_orders_dataset,order_delivered_customer_date,2965,2.98
40,olist_products_dataset,product_category_name,610,1.85
41,olist_products_dataset,product_name_lenght,610,1.85
42,olist_products_dataset,product_description_lenght,610,1.85
43,olist_products_dataset,product_photos_qty,610,1.85
5,olist_orders_dataset,order_delivered_carrier_date,1783,1.79
4,olist_orders_dataset,order_approved_at,160,0.16
44,olist_products_dataset,product_weight_g,2,0.01
45,olist_products_dataset,product_length_cm,2,0.01
46,olist_products_dataset,product_height_cm,2,0.01
47,olist_products_dataset,product_width_cm,2,0.01

In [14]:
olist_orders_dataset.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [5]:
olist_customers_dataset.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [ ]:
olist_geolocation_dataset.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [7]:
olist_order_payments_dataset.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [8]:
product_category_name_translation.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [9]:
olist_order_items_dataset.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [10]:
olist_order_reviews_dataset.describe()

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [11]:
olist_products_dataset.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [12]:
olist_sellers_dataset.describe()

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000